name: Deploy GH Pages

on:
  push:
    branches:
      - master
    paths:
      - 'docs/*.md'
      - 'docs/developer'
      - 'docs/logo/**/*'
      - '*.md'
      - '.github/workflows/pages.yml'

jobs:
  prepare-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v4
        with:
          path: master

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: 'gh-pages'
          path: gh-pages

      - name: Copy site files
        run: |
          cp master/docs/*.md gh-pages/
          rm gh-pages/docs-readme.md
          cp -r master/docs/developer gh-pages/
          cp master/CODE_OF_CONDUCT.md master/CONTRIBUTING.md gh-pages/_pages/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: gh-pages
          retention-days: 7

  deploy-gh-pages:
    runs-on: ubuntu-latest
    needs: prepare-artifact
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4